version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /temp/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    # links:
    #   - db

  web:  
    build: 
      context: .
      dockerfile: ./dev.Dockerfile
    ports:
      - "4000:4000"
    # volumes:
    #   - .:/app
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env

